# Generated by Django 4.0.5 on 2023-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='college_percent',
            field=models.FloatField(),
        ),
    ]
