# Generated by Django 4.0.5 on 2023-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_process', '0002_alter_candidate_college_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='technology',
            field=models.CharField(choices=[('python', 'PYTHON'), ('django', 'DJANGO'), ('sql', 'SQL'), ('react', 'REACT'), ('javascript', 'JAVASCRIPT')], default='python', max_length=100),
        ),
    ]
