# Generated by Django 4.0.5 on 2023-05-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_process', '0003_alter_candidate_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='inteviewquestion',
            name='question_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
