# Generated by Django 4.0.5 on 2023-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_process', '0005_interview_interviewquestion_remove_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Please Enter A Question Type', unique=True),
        ),
    ]
