# Generated by Django 4.0.5 on 2023-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_process', '0006_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('python', 'PYTHON'), ('react', 'REACT'), ('sql', 'SQL')], max_length=20),
        ),
    ]
